name: "Build Environment 🚜"
description: "Build environment and install dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20.19.1"
        cache: "npm"
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: "Cache Tools/Dependencies"
      uses: actions/cache@v4
      with:
        path: |
          /opt/hostedtoolcache/node/20.19.1/x64
          ~/.local/share/sf
        key: minlopro-dx-env-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: 'Build Environment & Install Salesforce CLI'
      shell: bash
      run: bash ./scripts/deploy/common/build.sh
