name: "Build Environment 🚜"
description: "Build environment and install dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: actions/setup-python@v5
      with:
        python-version: '>=3.10'
    - name: "Cache Tools/Dependencies"
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/sf
          ./bin
        key: minlopro-dx-env-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: "Build Environment & Install Salesforce CLI"
      shell: bash
      run: bash ./scripts/deploy/common/build.sh
