name: Build Environment 🚜
description: "Build Environment and Install Dependencies"

inputs:
  sfdx_auth_url:
    required: true
    type: string

outputs:
  target-org-alias:
    description: "Alias of locally authenticate Salesforce org"
    value: ${{ steps.auth-salesforce-org.outputs.SF_TARGET_ORG_ALIAS }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: "Cache Tools/Dependencies"
      uses: actions/cache@v4
      with:
        path: |
          /opt/hostedtoolcache/node/20.19.0/x64
          ~/.local/share/sf
        key: ${{ runner.os }}-minlopro-dx-tools-${{ hashFiles('**/package-lock.json') }}
    - name: 'Install Salesforce CLI'
      run: |
        bash ./scripts/deploy/common/build.sh
    - name: 'Authorize Target Org'
      id: auth-salesforce-org
      run: |
        bash ./scripts/deploy/common/authorize_org.sh --sfdxUrl "${{ inputs.sfdx_auth_url }}"
        SF_TARGET_ORG_ALIAS="$(bash ./scripts/util/set_target_org_compound_alias.sh)"; sf alias list
        echo "SF_TARGET_ORG_ALIAS=$SF_TARGET_ORG_ALIAS" >> $GITHUB_OUTPUT
