public with sharing class Application {
  //testcomment
  //    public static final fflib_Application.ServiceFactory Service = new fflib_Application.ServiceFactory(
  //            new Map<Type, Type>{
  //                    AdmDetailListManager.class => AdmDetailListManager.class,
  //            }
  //    );
  //
  //    public static final fflib_Application.UnitOfWorkFactory UnitOfWork = new fflib_Application.UnitOfWorkFactory(
  //            new List<SObjectType>{
  //                    User.SObjectType
  //            }
  //    );
  //
  //    public static final fflib_Application.SelectorFactory Selector = new fflib_Application.SelectorFactory(
  //            new Map<SObjectType, Type>{
  //                  User.SObjectType => UserSelector.class,
  //            }
  //    );
  //
  //    public static final fflib_Application.DomainFactory Domain = new fflib_Application.DomainFactory(
  //            Application.Selector,
  //            new Map<SObjectType, Type>{
  //                    User.SObjectType => Users.Constructor.class,
  //            }
  //    );
}
