name: "Auth Salesforce Org 🚜"
description: "Authenticate into Salesforce org and assign it unique alias"

inputs:
  target-org-alias:
    required: false
    description: "Target Salesforce org alias to set upon authentication"
  sfdx_auth_url:
    required: true
    description: "Target Salesforce org SFDX URL"

outputs:
  target-org-alias:
    description: "Alias of locally authenticated Salesforce org"
    value: ${{ steps.auth-salesforce-org.outputs.SF_TARGET_ORG_ALIAS }}
  target-org-instance-url:
    description: "Instance URL of locally authenticated Salesforce org"
    value: ${{ steps.auth-salesforce-org.outputs.SF_TARGET_ORG_INSTANCE_URL }}

runs:
  using: "composite"
  steps:
    - name: 'Authorize Salesforce Org'
      id: auth-salesforce-org
      shell: bash
      run: |
        bash ./scripts/deploy/common/authorize_org.sh "${{ inputs.sfdx_auth_url }}" "${{ inputs.target-org-alias }}"
        orgAlias=$(sf config get target-org --json | jq -r '.result[0].value')
        echo "SF_TARGET_ORG_ALIAS=$orgAlias" >> $GITHUB_OUTPUT
        echo "SF_TARGET_ORG_INSTANCE_URL=$(sf org display -o $orgAlias --json | jq -r '.result.instanceUrl')" >> $GITHUB_OUTPUT
    - name: 'Listing Organization Limits'
      shell: bash
      run: sf limits api display
