@IsTest
private class DlrsAccountOpportunitiesRollupTest {
    @TestSetup
    static void setup() {
        // dlrs__LookupRollupSummary2.Account_AvgOfOpportunitiesAmount
    }

    @IsTest
    static void testCalculateAvgOfRelatedOpportunitiesAmountOnParentAccount() {
        // Runs as ...
        // TODO

        /**
         * The purpose of the test is to verify that DLRS config works as expected;
         */
    }
}
