name: "Run Apex Tests 🚇"
description: "Runs Apex Tests in target Salesforce org, sends Slack alerts & generates results report"

inputs:
  target-org-alias:
    required: true
    description: "Locally authenticated Salesforce org alias"
  class-names:
    required: false
    description: "Apex Test class names separated by colon character"
  slack-webhook-url:
    required: false
    description: "Slack Webhook URL to post test results to"

runs:
  using: "composite"
  steps:
    - name: 'Invoke Apex Tests'
      id: run-apex-tests
      continue-on-error: true
      shell: bash
      run: |
        # Default boolean flag value
        echo "success=false" >> $GITHUB_OUTPUT
        
        # Create temporary flags directory
        flagsDir=$(mktemp -d) && trap 'rm -rf $flagsDir' EXIT
        
        # Parse Apex Test class names if set;
        apexClassNames="${{ inputs.class-names }}"
        apexClassNames="${apexClassNames//[[:space:]]/}"
        if [ -n "$apexClassNames" ]; then
          touch "$flagsDir/class-names"
          IFS=':' # Set colon as the field separator
          for item in ${apexClassNames}; do
            echo "$item" >> "$flagsDir/class-names"
          done
        fi
        
        # Invoke Apex Tests saving results in a dedicated folder
        sf apex run test \
          --target-org "${{ inputs.target-org-alias }}" \
          --flags-dir "$flagsDir" \
          --code-coverage \
          --output-dir "test-results" \
          --wait 30 \
          --concise
    - name: 'Send Slack Alert'
      if: ${{ inputs.slack-webhook-url != '' }}
      uses: slackapi/slack-github-action@v2.1.0
      with:
        webhook: ${{ inputs.slack-webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "attachments": [
              {
                "color": "${{ steps.run-apex-tests.outcome == 'success' && 'good' || 'danger' }}",
                "text": "Apex Tests ${{ steps.run-apex-tests.outcome == 'success' && '_passed_' || '🔻 *failed* 🔻' }} in *${{ inputs.target-org-alias }}* Salesforce org. \n See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run> for more details.",
                "mrkdwn_in": ["text"]
              }
            ]
          }
    - name: 'Generate Apex Tests Report'
      if: always()
      uses: dorny/test-reporter@v2
      with:
        name: Apex Tests
        path: test-results/test-result-*-junit.xml
        reporter: java-junit
        report-title: 'Apex Tests'
        badge-title: 'apex-tests'
        list-suites: 'all'
        list-tests: 'failed'
        fail-on-error: 'true'
        fail-on-empty: 'true'
    - name: 'Append Success Image'
      shell: bash
      run: |
        # Append success image
        IMAGES=(
          "https://i.giphy.com/M0ZoXrSPttN6czwKnx.webp"
          "https://i.giphy.com/OlNDlH5bAGMncqVFua.webp"
          "https://i.giphy.com/Ov09jGgEThFKpxZ9eC.webp"
          "https://i.giphy.com/aPy1iDreYN5DIVtoMk.webp"
          "https://i.giphy.com/Yu3CQVzP8oSOemmKqQ.webp"
          "https://i.giphy.com/vOsRhrnqdyFnPp2OrG.webp"
          "https://i.giphy.com/eZQVUNYA00hItBCHNq.webp"
        )
        RANDOM_IMAGE=${IMAGES[$RANDOM % ${#IMAGES[@]}]}
        echo "![Img]($RANDOM_IMAGE \"Img\")" >> $GITHUB_STEP_SUMMARY
