name: Build Env 🚜
run-name: "Build Environment and Install Dependencies (${{ github.head_ref || github.ref_name }})"

on:
  workflow_call:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        type: choice
        default: "Minlopro DevHub"
        options:
          - "Minlopro Prod"
          - "Minlopro DevHub"
      welcome-keyword:
        required: true
        type: string
      sfdx_auth_url:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

env:
  SF_CLI_VERSION: "2.77.6"

# Jobs
jobs:
  build-env:
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: "Cache Tools/Dependencies"
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache/node/20.19.0/x64
            ~/.local/share/sf
          key: ${{ runner.os }}-minlopro-dx-tools-${{ hashFiles('**/package-lock.json') }}
      - name: 'Install Salesforce CLI'
        run: |
          echo "Welcome word = ${{ inputs.welcome-keyword }}"
          bash ./scripts/deploy/common/build.sh
      - name: 'Authorize Target Org'
        run: |
          bash ./scripts/deploy/common/authorize_org.sh --sfdxUrl "${{ inputs.sfdx_auth_url }}"
#          SF_TARGET_ORG_ALIAS="$(bash ./scripts/util/set_target_org_compound_alias.sh)"; sf alias list
#          echo "SF_TARGET_ORG_ALIAS=$SF_TARGET_ORG_ALIAS" >> $GITHUB_ENV
      
