name: Deploy Source 🎯

# Trigger Events
on:
  schedule:
    # Runs "At 07:00 on every day-of-week from Monday through Friday"
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
    branches:
      - develop
  push:
    branches:
      - develop

# Jobs
jobs:
  # Event = 'Push'
  deploy-source-to-org:
    runs-on: ubuntu-latest
    environment: "Minlopro DevHub"
    env:
      SF_USERNAME: ${{ vars.SF_USERNAME }}
      SF_CLIENT_ID: ${{ vars.SF_CLIENT_ID }}
      SF_CLIENT_SECRET: ${{ vars.SF_CLIENT_SECRET }}
      SF_BASE_URL: ${{ vars.SF_BASE_URL }}
      SF_TOKEN_URL_PATH: ${{ vars.SF_TOKEN_URL_PATH }}
      SF_AUTH_PROVIDER_URL_PATH: ${{ vars.SF_AUTH_PROVIDER_URL_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: 'Install Salesforce CLI & Authorize Target Org'
        run: |
          bash ./scripts/deploy/build.sh
          echo ${{secrets.DEV_HUB_AUTH_URL}} | bash ./scripts/deploy/authorize_org.sh
      - name: 'Deploy Source to Target Org'
        run: |
          bash ./scripts/deploy/replace_variables.sh
          npm run sf:manifest:create
          npm run src:deploy:full
      - name: 'Custom Post-Deployment Steps'
        run: |
          targetOrgAlias=$(bash ./scripts/util/get_target_org_alias.sh)
          bash ./scripts/util/run_apex_script.sh $targetOrgAlias set_up_org_admin
          bash ./scripts/util/run_apex_script.sh $targetOrgAlias set_up_digex_guest_user
          echo $targetOrgAlias | bash ./scripts/util/delete_all_apex_logs.sh
          echo $targetOrgAlias | bash ./scripts/util/delete_obsolete_flow_versions.sh
  run-apex-tests:
    needs: [ deploy-source-to-org ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: 'Install Salesforce CLI & Authorize Target Org'
        run: |
          bash ./scripts/deploy/build.sh
          echo ${{secrets.DEV_HUB_AUTH_URL}} | bash ./scripts/deploy/authorize_org.sh
      - name: 'Run All Apex Tests with Coverage'
        run: npm run sf:apex:tests:coverage
  run-pmd-checks:
    needs: [ deploy-source-to-org ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: 'Install NPM Dependencies'
        run: npm install
      - name: 'Run Apex Static Code Analysis (PMD)'
        run: npm run pmd:html
      - name: 'Upload PMD Report as Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: apex-pmd-report
          path: build/apex-pmd-report.html
          retention-days: 5
