name: Playground 🐚
run-name: "Playground Workflow Run 🐚"

on:
#  pull_request:
#    types: [ opened, synchronize, reopened ]
  schedule:
    - cron: "0 11 * * 3"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Deployment/Environment"
        required: true
        type: environment
        default: "Minlopro DevHub"

permissions:
  contents: read
  id-token: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  demo:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    environment: ${{ inputs.environment || 'Minlopro DevHub' }}
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
      SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Build Environment 🚜"
        uses: ./.github/actions/build-env
        env:
          SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
      - name: "Auth Salesforce Org 🎫"
        id: auth-org
        uses: ./.github/actions/auth-salesforce-org
        with:
          sfdx-auth-url: ${{ env.SF_AUTH_URL }}
      - name: "Confirm Auth ✅"
        shell: bash
        run: |
          echo "::notice::Org Alias: ${{ steps.auth-org.outputs.target-org-alias }}"
          echo "::debug::Instance URL: ${{ steps.auth-org.outputs.target-org-instance-url }}"
