name: Release 🔫

# Trigger Events
on:
  workflow_dispatch:
    branches:
      - release/**
  push:
    branches:
      - release/**

# Jobs
jobs:
  sf-validate-deployment:
    runs-on: ubuntu-latest
    environment: "Minlopro Prod"
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
      SF_CCF_APP_CLIENT_ID: ${{ secrets.SF_CCF_APP_CLIENT_ID }}
      SF_CCF_APP_CLIENT_SECRET: ${{ secrets.SF_CCF_APP_CLIENT_SECRET }}
      SF_GITHUB_WEBHOOK_SECRET: ${{ vars.SF_GITHUB_WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Salesforce CLI & Authorize Production Org'
        run: |
          bash ./scripts/deploy/build.sh
          bash ./scripts/deploy/authorize_org.sh --sfdxUrl $SF_AUTH_URL --orgAlias Prod
      - name: "Run PRE-Deploy Scripts"
        run: echo "Prod" | bash ./scripts/deploy/pre/run_pre.sh
      - name: 'Deploy Source to Target Org'
        run: |
          echo ">>> Validating deployment and getting Job ID..."
          sf org display -o Prod
      - name: 'Run POST-Deploy Scripts'
        run: echo "Prod" | bash ./scripts/deploy/post/run_post.sh
  sf-quick-deploy:
    needs: [ sf-validate-deployment ]
    runs-on: ubuntu-latest
    environment: "Minlopro Prod"
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
      SF_CCF_APP_CLIENT_ID: ${{ secrets.SF_CCF_APP_CLIENT_ID }}
      SF_CCF_APP_CLIENT_SECRET: ${{ secrets.SF_CCF_APP_CLIENT_SECRET }}
      SF_GITHUB_WEBHOOK_SECRET: ${{ vars.SF_GITHUB_WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Salesforce CLI & Authorize Production Org'
        run: |
          bash ./scripts/deploy/build.sh
          bash ./scripts/deploy/authorize_org.sh --sfdxUrl $SF_AUTH_URL --orgAlias Prod
      - name: 'Quick Deploy By Job ID'
        run: |
          echo ">>> Deploying by Job ID..."
          sf org display -o Prod
