name: Release 🚀

on:
  workflow_dispatch:
    inputs:
      doQuickDeploy:
        type: boolean
        description: 'Do Quick Deploy?'
        default: false
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  run-deploy-validate:
    runs-on: ubuntu-22.04
    environment: "Minlopro Prod"
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
      SF_ADMIN_EMAIL: ${{ vars.SF_ADMIN_EMAIL }}
      SF_GITHUB_WEBHOOK_SECRET: ${{ secrets.SF_GITHUB_WEBHOOK_SECRET }}
      SF_GOOGLE_API_KEY: ${{ secrets.SF_GOOGLE_API_KEY }}
      SF_GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.SF_GOOGLE_RECAPTCHA_SITE_KEY }}
      SF_GOOGLE_RECAPTCHA_SITE_SECRET: ${{ secrets.SF_GOOGLE_RECAPTCHA_SITE_SECRET }}
    outputs:
      job-id: ${{ steps.validate-deployment.outputs.SF_VALIDATION_JOB_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Build Environment 🚜"
        uses: ./.github/actions/build-env
        env:
          SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
      - name: "Auth Production Org 🎫"
        uses: ./.github/actions/auth-salesforce-org
        with:
          sfdx-auth-url: ${{ env.SF_AUTH_URL }}
          target-org-alias: "Prod"
      - name: "Run PRE-Deploy Scripts"
        run: |
          git checkout main; git pull
          echo "Prod" | bash ./scripts/deploy/pre/run_pre.sh
      - name: "Generate Release Manifests (pull_request)"
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          releaseBranchName="${{github.head_ref}}"
          git checkout "$releaseBranchName"; git pull
          bash ./scripts/deploy/common/generate_manifest.sh \
            --mode "delta" \
            --target-org "Prod" \
            --from-ref "main" \
            --to-ref "$releaseBranchName"
      - name: "Generate Release Manifests (workflow_dispatch)"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          releaseBranchName="${GITHUB_REF#refs/heads/}"
          git checkout "$releaseBranchName"; git pull
          bash ./scripts/deploy/common/generate_manifest.sh \
            --mode "delta" \
            --target-org "Prod" \
            --from-ref "main" \
            --to-ref "$releaseBranchName"
      - name: 'Validate Deployment And Extract Job ID'
        id: validate-deployment
        run: |
          echo "Prod" | bash ./scripts/release/release_validate.sh
          RELEASE_JOB_ID=$(cat "build/release_job_id.txt")
          echo "SF_VALIDATION_JOB_ID=$RELEASE_JOB_ID" >> "$GITHUB_OUTPUT"
  run-quick-deploy:
    if: ${{ github.event.inputs.doQuickDeploy == 'true' }}
    needs: [ run-deploy-validate ]
    runs-on: ubuntu-22.04
    environment: "Minlopro Prod"
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: "Build Environment 🚜"
        uses: ./.github/actions/build-env
        env:
          SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
      - name: "Auth Production Org 🎫"
        uses: ./.github/actions/auth-salesforce-org
        with:
          sfdx-auth-url: ${{ env.SF_AUTH_URL }}
          target-org-alias: "Prod"
      - name: 'Quick Deploy By Job ID'
        run: |
          jobId="${{ needs.run-deploy-validate.outputs.job-id }}"
          inputsFile="release-deploy-inputs.txt"
          touch $inputsFile
          echo "Prod" >> $inputsFile
          echo "$jobId" >> $inputsFile
          bash ./scripts/release/release_deploy.sh < $inputsFile
