name: Reset Destructive Manifests ⚙️

on:
  workflow_dispatch:

jobs:
  reset-destructive-manifests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Build Environment 🚜"
        uses: ./.github/actions/build-env
        env:
          SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
      - name: "Reset Manifests & Commit Changes"
        run: |
          git config user.name "github-actions[bot] 🤖"
          git config user.email "${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com"
          bash ./scripts/automations/reset_and_commit_destructive_manifests.sh
